sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
  - yarn install
script:
  - yarn build
  - docker build -t kikoken/climate-frontend .

deploy:
  provider: script
  script:
    docker push kikoken/climate-frontend;
  branch: master